kibot:
  version: 1
global:
  out_dir: output
preflight:
  check_zone_fills: true
  erc: true
  drc: true

outputs:
  - name: Info
    type: info

  - name: Report
    type: report

  - name: BoM
    type: bom
    options:
      format: 'CSV'
      csv:
        quote_all: true
        hide_pcb_info: true
        hide_stats_info: true
      columns:
        - Row
        - Quantity Per PCB
        - References
        - Vendor
        - Value
        - Footprint
        - Description
      group_fields: ['Vendor']
      parse_value: false
      normalize_values: false

  - name: 'print_sch'
    type: pdf_sch_print

  - name: 'gerbers'
    type: gerber
    dir: gerber
    options:
      exclude_edge_layer: false
    layers:
      - 'copper'
      - 'technical'
      - 'user'

  - name: 'd356'
    type: netlist
    dir: gerber
    options:
      format: "ipc"

  - name: drill
    type: excellon
    dir: gerber

  - name: position
    type: position
    dir: gerber

  - name: 3D
    type: step
    dir: 3D
