name: Automation

on: [push, pull_request, workflow_dispatch]

jobs:
  fab:
    name: Fab Outputs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: output
        config: .github/kibot-fab.yaml
    - name: Full output
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Everything
        path: output
    - name: Fab output
      id: fab
      uses: actions/upload-artifact@v4
      with:
        name: mps-io
        compression-level: 9
        if-no-files-found: 'error'
        path: |
          output/**/*.drl
          output/**/*.gbr*
          output/**/*.d356
          output/**/*.pos
          output/**/*bom*

  upstreamdiff:
    name: Upstream Diff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Tag base
      run: |
        git tag xxBASE ee31886a00501e03c37f51481febb71d61286b3d
        git log -n1 xxBASE
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: diff
        config: .github/kibot-diff.yaml
    - name: Upload Diff
      id: usdiff
      uses: actions/upload-artifact@v4
      with:
        name: upstream-diff
        compression-level: 9
        if-no-files-found: 'error'
        path: diff

  prdiff:
    name: PR Diff
    runs-on: ubuntu-latest
    if: ${{ github.base_ref }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Tag PR base
      run: |
        git tag xxBASE ${{ github.event.pull_request.base.sha }}
        git log -n1 xxBASE
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: diff
        config: .github/kibot-diff.yaml
    - name: Upload Diff
      id: prdiff
      uses: actions/upload-artifact@v4
      with:
        name: pr-diff
        compression-level: 9
        if-no-files-found: 'error'
        path: diff
